#
# Module manifest for module 'Matrix'
#
# Generated by: James Brundage
#
# Generated on: 8/10/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Matrix.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '1ea87d5e-babe-42d9-97fa-68775e5335af'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start-Automating'

# Copyright statement for this module
Copyright = '2026'

# Description of the functionality provided by this module
Description = 'Matrix Transforms with PowerShell'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'Matrix.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Matrix', 'Get-Matrix'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = 'Matrix'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 
    @(
        'Matrix4x4', 'Matrix3x2', 'Matrix2d', 'Matrix3d','Quaternion'
        'Scale',
        'ScaleX',
        'ScaleY',
        'ScaleZ',        
        'Scale3D',
        'Skew',
        'SkewX',
        'SkewY',
        'Rotate',
        'RotateX',
        'RotateY',
        'RotateZ',        
        'Rotate3D',
        'Translate',
        'Translate3d',
        'TranslateX',
        'TranslateY',
        'TranslateZ'
    )


# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PoshWeb/Matrix/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PoshWeb/Matrix/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Matrix 0.1

* Initial Matrix Module (#1)
* `Matrix.ps1` makes matrices (#2)
* `Matrix` has a build (#3)
* `Matrix` extended types
  * `[Numerics.Matrix3x2]`
    * `.Points` contains the points in the matrix (#4)
    * `.CSS` renders the matrix as CSS (#5)
    * `.MathML` renders the matrix as MathML (#33)
    * `.Html` renders the matrix as MathML in HTML (#36)
    * `DefaultDisplay` limits the number of displayed properties (#34)
  * `[Numerics.Matrix4x4]`
    * `.Points` contains the points in the matrix (#6)
    * `.CSS` renders the matrix as CSS (#7)
    * `.MathML` renders the matrix as MathML (#31)
    * `.Html` renders the matrix as MathML in HTML (#35)
    * `DefaultDisplay` limits the number of displayed properties (#32)
  * `[Numerics.Quaternion]`
    * `.CSS` renders the matrix as CSS (#12)
    * `.MathML` renders a quaternion as MathML (#37)
    * `.Html` renders the matrix as MathML in HTML (#38)
    * `DefaultDisplay` limits the number of displayed properties (#39)
* `Matrix` aliases provide CSS Compatibility (#8)
* `Matrix` has an autogenerated `README.md.ps1` (#10)
* `Matrix` website demonstrates matrix
  * `layout.ps1` lays out pages (#16)
  * `deploy.ps1` deploys the site (#22)
  * `config.ps1` configures the site (#23)
  * `/_includes/`
    * `/_includes/FeatherIcon` includes feather icons (#24)
    * `/_includes/Palette` includes a palette (#25)
    * `/_includes/CopyCode` includes a "copy code" button (#26)
    * `/_includes/Sitemap` includes a sitemap (#27)
    * `/_includes/Menu` includes a menu (#29)
  * `/Matrix.html.ps1` is the site root (#14)
    * `/matrix/css`
      * `/matrix/css/compatible` shows side by side comparisons (#17)
      * `/matrix/css/transform` shows some matrix transform examples (#18)
    * `/matrix/dotnet` explains matrices in DotNet (#19)
    * `/matrix/svg` shows matrices in SVG (#28)
    * `/matrix/powershell` shows matrices in PowerShell (#20)

'@


        PSIntro = @'
Matrix math is tedious.  This module lets us avoid having to do it.

We can represent changes in space using a matrix.

In CSS, these are called [Transform Functions](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/transform-function)

|Dimension|Transform Function|.NET type|
|:-:|:-:|:-:|
|`2D`|`matrix()`|`[Numerics.Matrix3x2]`|
|`3D`|`matrix3d()`|`[Numerics.Matrix4x4]`|

The module allows you to make, modify, and use matrix transforms.

It supports almost identical syntax to the CSS.

We can use Matrix to make CSS transforms,
and we can manipulate objects in 2D or 3D the same way a webpage would.
'@
        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

    Recommends = 'Vector'

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

